### ISSUE TITLE
netcoreapp2.0 vs netstandard2.0

### ISSUE THREAD

**Issue by TheAngryByrd** [YoloDev/YoloDev.Expecto.TestSdk#13]
I'm starting to hit a wall with https://github.com/dotnet/cli/issues/5346#issuecomment-378650606.  The issue seems to be that setting the test sdk to `netcoreapp2.0` can cause weird dependency issues.  I was wondering why `netcoreapp2.0` was chosen over `netstandard2.0`.  I've changed the code locally to use `netstandard2.0` and it still seems to work.  I can make a PR if this seems acceptable.

**Comment by Alxandr** [comment]
There was a strong requirement to have it be `netcoreapp2.0`. I don't remember what it was, but I think the adapter (build by this repo) was not picked up if it was `netstandard2.0`. It's been a while though, so I won't say for certain, and it also might have changed since. When you said "still seems to work", does that mean that it built? Or that it ran the tests? Or what exactly worked?

**Comment by TheAngryByrd** [comment]
So I changed netcoreapp2.0 to netstandard2.0 and then ran `dotnet test` on the test project.  Everything still ran as expected.

**Comment by Alxandr** [comment]
You can make a PR if you want to. Travis and AppVeyor should (hopefully) tell me if anything is broken 🙂. I also wanted to have it be `netstandard`, but it didn't work when I started out.

**Comment by TheAngryByrd** [comment]
Seems like I had an issue with my paket.lock file. Gonna close this.
