### ISSUE TITLE
Different Environment.CurrentDirectory 

### ISSUE THREAD

**Issue by rodrigovidal** [YoloDev/YoloDev.Expecto.TestSdk#2]
Hi @Alxandr, 

I have a question, so far I have been using the following command to run Expecto tests.

dotnet run --project src/{projectname}.tests/{projectname}.tests.fsproj

The thing is when I do this the Environment.CurrentDirectory is the root path of the project but when I run doing the "dotnet test" command from the root the CurrentDirectory is {projectPath}/bin/Debug/netcoreapp2.0. 

Given that some integration tests broke because of this difference. What do you think would be the best way to handle this?

Thanks for this tool btw.

**Comment by Alxandr** [comment]
Hmm. I would think this would be the same for all of the test runners (could you do a quick test to see if you get the same with XUnit for instance?). If that's the case than the functionality is derived from vstest runner (which is what runs when you do `dotnet test`) and should not be changed by this test adapter. AFAIK; I don't change `CurrentDirectory` currently, but that *might* be a bug.

If the conclusion is that the current behavior is correct though; I would say that you should probably create a build script of some kind to ensure you get the correct behavior. Whether that be to ensure that the `CurentDirectory` is always at the git root, or it's always at the test project bin root is up to you.

An alternative would be to set an environment variable, that you read in the test, and change the `CurrentDirectory`. Though I have a feeling that could lead to flaky tests... It shouldn't because the different assemblies are tested in serial, but that is an implementation detail that **could** conceivably change in the future...

**Comment by Alxandr** [comment]
Stale issue.
