### ISSUE TITLE
Use dot as a separator instead of slash

### ISSUE THREAD

**Issue by cmeeren** [YoloDev/YoloDev.Expecto.TestSdk#26]
When the VS test explorer renders the test tree, it seems to use dot as a separator (if grouping by namespace/class).

Consider the following tests:

```f#
[<Tests>]
let tests =
  testList "Domain" [
    testList "Username" [
      testList "create" [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input length is > 100" ignore
        testCase "trims the input if Ok" ignore
      ]
    ]
    testList "CustomerNumber" [
      testList "create" [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input is non-numeric" ignore
        testCase "returns Ok if the input is numeric" ignore
      ]
    ]
  ]
```

Test Explorer shows it like this:

![image](https://user-images.githubusercontent.com/7766733/68758044-59411380-060d-11ea-8add-572661847708.png)

All tests appear in a flat list. This makes it hard to read, hard to find relevant tests, and hard to select a related group of tests to run.

It would be much more useful if Test Explorer could show it as a tree. AFAIK this would only require using `.` instead of `/` as a separator in the hierarchy.

It can be worked around to some extent by adding dots to the end of each test list name:

```f#
[<Tests>]
let tests =
  testList "Domain." [
    testList "Username." [
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input length is > 100" ignore
        testCase "trims the input if Ok" ignore
      ]
    ]
    testList "CustomerNumber." [
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input is non-numeric" ignore
        testCase "returns Ok if the input is numeric" ignore
      ]
    ]
  ]
```

![image](https://user-images.githubusercontent.com/7766733/68758297-d66c8880-060d-11ea-8b01-30855002b581.png)

But it's not optimal: It requires changing the names, it still renders the slashes, and seems to only work for the last levels (e.g. `Domain./CustomerNumber` hasn't been split, and if there are single sibling test cases of nested tests lists, then they are not shown grouped in the same way).

If you used `.` instead of `/` as a separator, I think that would give a much better experience in the VS test explorer. 🙂

Or if you have any other idea about how to improve this, that would be great!

**Comment by cmeeren** [comment]
Just to be clear about the sibling test stuff I mentioned, in case it's relevant:

```f#
[<Tests>]
let tests =
  testList "Domain." [
    testList "Username." [
      testCase "Some other username test" ignore
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input length is > 100" ignore
        testCase "trims the input if Ok" ignore
      ]
    ]
    testList "CustomerNumber." [
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input is non-numeric" ignore
        testCase "returns Ok if the input is numeric" ignore
      ]
    ]
  ]
```

![image](https://user-images.githubusercontent.com/7766733/68758865-e3d64280-060e-11ea-942c-4de5ddbde73f.png)

**Comment by Alxandr** [comment]
This would definitely be an improvement, though I'm not sure it's something really doable in this project, cause I'm pretty sure we delegate name creation to `Expect` itself. That being said; I would definitely take a PR to this if you figure out how to do it. Right now I simply don't have the time to look into it myself.

**Comment by cmeeren** [comment]
> I'm pretty sure we delegate name creation to `Expect` itself

Thanks, I'll take this to the Expecto repo, then. :)

**Comment by haf** [comment]
@yolodev Would you be open to merging bits and pieces of this repo into the Expecto repo while continuing your stewardship of the code?

**Comment by haf** [comment]
This issue depends on whether the FlatTest or the tree structure is being used as the backing data

**Comment by haf** [comment]
Also if you’re using the flat tests maybe the hierarchy can be rebuilt from splitting on slash

**Comment by Alxandr** [comment]
@haf Sorry, I completely dropped the ball on this one. I thought I'd responded, but apparently I'd only thought of my response, and not written it 😛. I'm more than open to any of this code being begged, borrowed, or stolen by just about anyone, and merging parts of it into expecto if that's what you want is completely fine by me. To be honest, I've not written F# code in quite a while now, so I've not used this project myself for a good while. That isn't to say I don't want to support it, merely that it's definitely harder for me to do so as I have the extra overhead of getting back into F# (and setting up my environment, cause it's generally far between occurances) for each time I have to fix something. When it comes to how we discover tests; I *think* this is what function we call from expecto: https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/src/YoloDev.Expecto.TestSdk/discovery.fs#L58. You probably know better than me what it supports wrt. format and name-production.

**Comment by MNie** [comment]
FYI @Alxandr #364 was merged in Expecto. So you could specify a separator by a `join-by` flag. Available options are `.` and `/` ;)

**Comment by Alxandr** [comment]
> but I don't see an option to somehow gather Expecto config in TestSdk

I don't understand what you mean here?

**Comment by MNie** [comment]
@Alxandr I mean getting information about the passed configuration to Expecto, so we wouldn't parse manually a cmd line args. I assume it would be needed since after an update of Expecto package following lines need to be adjusted (since Expecto `FlatTest` `name` property is a `string list` instead of `string`):
- [discovery.fs line 13](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/4a9d00b22edeeed5819ab36c06e4daabfd4b0b38/src/YoloDev.Expecto.TestSdk/discovery.fs#L13)
- [executon.fs line 127](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/4a9d00b22edeeed5819ab36c06e4daabfd4b0b38/src/YoloDev.Expecto.TestSdk/execution.fs#L127)
- [execution.fs line 143](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/4a9d00b22edeeed5819ab36c06e4daabfd4b0b38/src/YoloDev.Expecto.TestSdk/execution.fs#L143)

But looking at [Settings.fs line 114](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/4a9d00b22edeeed5819ab36c06e4daabfd4b0b38/src/YoloDev.Expecto.TestSdk/settings.fs#L114) it seems that it is a preferable way to get "config" information that way (via parsing cmd args). Since `ExpectoConfig` is not available outside of Expecto (it is a private type). Am I right?

**Comment by Alxandr** [comment]
Sorry, I'm not processing this right now, and it's been a long time since I've really touched the code, so I won't say for 100% that I remember this correctly, but as far as I can remember there are no cmd arguments involved with in this library. All cmd arguments are handled by VSTest, and no cmd arguments are passed to expect. Rather, expect takes an argument type (a list of DUs, as far as I can remember). Whether or not there's been breaking changes there in version 9 of expect, I don't know, as I've not looked at it. Also; if what you mean by a `join-by` flag is a command line argument, than that will not help this library, because test discovery does not involve command line arguments as far as I can remember. That being said, if they've added it as a command line argument, it's likely it's also been added as a function/option somewhere, and that can definitely be looked into.

If you would like to look into this yourself, I will gladly review a PR for this project. If not, I'll likely get to it after a while. I can't promise expediency though, as I've not been doing F# for ages, and I currently don't even have a set up environment for it.

**Comment by cmeeren** [comment]
There's bee a few breaking changes in Expecto 9, but in any case, YoloDev must be updated because the current package requires Expecto < 9.

As I understand it, dot is now the new default separator in Expecto, which means that if you just update this library to depend on Expecto 9, this issue may get fixed automatically.

**Comment by cmeeren** [comment]
Thanks! Grouping by project -> namespace -> class now produces the expected output (as long as the hierarchy is at least three levels deep including the test; otherwise it shows `<Empty namespace>` for the namespace level, which I guess is fine)
