### ISSUE TITLE
Upper bound of System.Collections.Immutable dependency needs to be raised

### ISSUE THREAD

**Issue by baronfel** [YoloDev/YoloDev.Expecto.TestSdk#38]
in order for this package to be compatible with .net 5.0 the upper bound on System.Collections.Immutable (which is currently set [here](https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/Packages.props#L11)) needs to be unlocked, otherwise this package prevents usage of the 5.0 RCs (and eventually stables). Since the rc1 dropped today and has a go-live license I figured now was the time to go ahead with this issue.

**Comment by Alxandr** [comment]
Oh joy. Not to this issue in general, but I'm not sure this repository currently builds correctly 😛. I can't promise when I'll get around to this - but if anyone want's to tackle it I can at least promise to be available for PR reviews/help.

**Comment by Alxandr** [comment]
See https://github.com/YoloDev/YoloDev.Expecto.TestSdk/pull/35 and https://github.com/YoloDev/YoloDev.Expecto.TestSdk/pull/34 for context. My guess is that part of #34 needs to be reverted.

**Comment by cmeeren** [comment]
@Alxandr It seems this fix was never released. Can you release it on NuGet?

**Comment by Alxandr** [comment]
You're right. I never got around to look at deployments (it's currently broken). I can probably take a look at it next week (I'm starting my vacation now so I have some spare time).

**Comment by Alxandr** [comment]
I apologies for the delay here. It turns out once vacation start the family starts assuming you have all this free time and can use it to do misc tasks 😛. I'm looking at the deployment process for this repository (albeit a bit indirectly) and hopefully so that I can fix it For Good™️.

Just as a note - I don't use F# anymore, and I'm mostly just trying to maintain this repo because some people seem to be using it. But it also means whenever new issues shows up (which tends to be seldom) I have to go find a computer that's set up for F# development, or set one up anew. @gdziadkiewicz has been added as a maintainer - but I need to fix the deployment. But if you have any stake in this project and would like to help maintain this project let me know.

**Comment by cmeeren** [comment]
> But if you have any stake in this project and would like to help maintain this project let me know.

Not sure this was aimed at me (as the most recent commenter) or the general "anyone". In any case, my "OSS maintenance quota" is unfortunately already past its limits.

Perhaps @haf could get involved, since Expecto uses this test runner? (At least for its template.)

**Comment by Alxandr** [comment]
You *and* everyone 😉. But not with expectations. Mostly just saying it to manage expectations.

**Comment by haf** [comment]
Well, the four sponsors I got when I tried to make a living out of OSS will have covered just the cost of the recording equipment I bought to make videos by next summer. I'm also trying to start a new company right now, so it's safe to say that my time is lacking right now.

**Comment by Alxandr** [comment]
I've uploaded a new version to nuget (0.11.1). Just manually uploaded the nupkg for now. I don't like the current versioning strategy, but I had to get something working, then I can work on improving it later.
